# Generated by Django 2.1.3 on 2018-11-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_donationtmade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationtmade',
            name='Amount',
        ),
        migrations.AddField(
            model_name='donationtype',
            name='Amount',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
