# Generated by Django 2.1.3 on 2018-11-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_donationtype_monthlycomitment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationtype',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
